<% repository_name = `git rev-parse --show-toplevel`.split('/').last.strip %>

default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: <%= "#{repository_name}_development" %>

test:
  <<: *default
  database: <%= "#{repository_name}_test" %>

production:
  <<: *default
  database: <%= "#{repository_name}_production" %>
